version: '3.8'
services:
  ewm-stats-server:
    build: ./stats-service/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - ewm-stats-db
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
#---------------------------------------------------------------------
  ewm-stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#--------------------------------------------------------------------
  ewm-main-service:
    build: ./main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
     - ewm-stats-server
     - ewm-main-service-db
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-main-service-db:5432/ewm-main-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - STATS_SERVER_URL=http://stats-server:9090
#--------------------------------------------------------------------
  ewm-main-service-db:
    image: postgres:14-alpine
    container_name: ewm-main-service-db
    ports:
      - "6542:5432"
    environment:
        - POSTGRES_DB=ewm-main-service
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
